name: b2b_solution
description: "CPPC B2B PORTAL"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.1  # สำหรับ swipe actions
  infinite_scroll_pagination: ^4.0.0  # สำหรับ pagination
  
  # State Management
  provider: ^6.1.1
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  pretty_dio_logger: ^1.3.1  # สำหรับ debug network calls
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5
  url_launcher: ^6.1.12
  path_provider: ^2.1.2
  mime: ^1.0.5
  dartz: ^0.10.1  # สำหรับ Either type ใน Clean Architecture
  logger: ^2.0.2+1  # สำหรับ logging

  # Authentication
  flutter_secure_storage: ^9.0.0  # สำหรับเก็บ sensitive data
  
  # Charts
  fl_chart: ^0.66.0  # สำหรับทำกราฟ
  
  # View PDF
  syncfusion_flutter_pdfviewer: ^24.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  mockito: ^5.4.4  # สำหรับ testing
  freezed: ^2.4.7  # สำหรับ code generation

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700